import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:simple_ledger/domain/services/csv_export_service.dart';
import 'package:simple_ledger/domain/services/recurring_service.dart';
import 'package:simple_ledger/presentation/providers/database_provider.dart';
import 'package:simple_ledger/presentation/providers/recurring_provider.dart';
import 'package:simple_ledger/presentation/providers/transactions_provider.dart';
import 'package:simple_ledger/presentation/screens/accounts/accounts_screen.dart';
import 'package:simple_ledger/presentation/screens/home/home_screen.dart';
import 'package:simple_ledger/presentation/screens/input/input_screen.dart';
import 'package:simple_ledger/presentation/screens/reports/reports_screen.dart';
import 'package:simple_ledger/presentation/screens/search/search_screen.dart';

class MainScaffold extends ConsumerStatefulWidget {
  const MainScaffold({super.key});

  @override
  ConsumerState<MainScaffold> createState() => _MainScaffoldState();
}

class _MainScaffoldState extends ConsumerState<MainScaffold> {
  int _selectedIndex = 0;
  bool _fabVisible = true;
  double _lastScrollOffset = 0;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _runRecurring());
  }

  Future<void> _runRecurring() async {
    final db = ref.read(databaseProvider);
    final result = await RecurringService(db).processToday();
    if (!mounted) return;
    if (result.autoGenerated > 0) {
      ref.read(recurringSessionCountProvider.notifier).state =
          result.autoGenerated;
    }
    if (result.pendingCount > 0) {
      ref.invalidate(pendingRecurringProvider);
    }
  }

  bool _onScroll(ScrollNotification notification) {
    // 水平スクロール（TabBarView のタブ切り替えスワイプ等）は無視
    if (notification.metrics.axis != Axis.vertical) return false;
    // スクロール開始時に基準位置を同期（タブ切り替え後の誤検知を防ぐ）
    if (notification is ScrollStartNotification) {
      _lastScrollOffset = notification.metrics.pixels;
      return false;
    }
    if (notification is ScrollUpdateNotification) {
      final delta = notification.metrics.pixels - _lastScrollOffset;
      _lastScrollOffset = notification.metrics.pixels;
      if (notification.metrics.pixels <= 0) {
        if (!_fabVisible) setState(() => _fabVisible = true);
      } else if (delta > 4 && _fabVisible) {
        setState(() => _fabVisible = false);
      } else if (delta < -4 && !_fabVisible) {
        setState(() => _fabVisible = true);
      }
    }
    return false;
  }

  static const _pages = [
    HomeScreen(),
    ReportsScreen(),
    AccountsScreen(),
  ];

  Future<void> _exportCsv() async {
    final txAsync = ref.read(transactionsWithEntriesProvider);
    final txList = txAsync.valueOrNull ?? [];
    if (txList.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('エクスポートするデータがありません')),
      );
      return;
    }
    try {
      await CsvExportService().exportAndShare(txList);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context)
            .showSnackBar(SnackBar(content: Text('エクスポート失敗: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NotificationListener<ScrollNotification>(
        onNotification: _onScroll,
        child: _pages[_selectedIndex],
      ),
      bottomNavigationBar: NavigationBar(
        selectedIndex: _selectedIndex,
        onDestinationSelected: (i) => setState(() {
          _selectedIndex = i;
          _fabVisible = true;
          _lastScrollOffset = 0;
        }),
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.home_outlined),
            selectedIcon: Icon(Icons.home),
            label: 'ホーム',
          ),
          NavigationDestination(
            icon: Icon(Icons.bar_chart_outlined),
            selectedIcon: Icon(Icons.bar_chart),
            label: '決算',
          ),
          NavigationDestination(
            icon: Icon(Icons.account_balance_outlined),
            selectedIcon: Icon(Icons.account_balance),
            label: '勘定科目',
          ),
        ],
      ),
      floatingActionButton: _selectedIndex == 2
          ? null
          : AnimatedSlide(
              duration: const Duration(milliseconds: 200),
              offset: _fabVisible ? Offset.zero : const Offset(0, 1.5),
              curve: Curves.easeInOut,
              child: AnimatedOpacity(
                duration: const Duration(milliseconds: 200),
                opacity: _fabVisible ? 1.0 : 0.0,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    FloatingActionButton.small(
                      heroTag: 'search',
                      onPressed: () => Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (_) => const SearchScreen()),
                      ),
                      child: const Icon(Icons.search),
                    ),
                    const SizedBox(height: 8),
                    FloatingActionButton.small(
                      heroTag: 'export',
                      onPressed: _exportCsv,
                      child: const Icon(Icons.download_outlined),
                    ),
                    const SizedBox(height: 8),
                    FloatingActionButton(
                      heroTag: 'add',
                      onPressed: () => Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (_) => const InputScreen()),
                      ),
                      child: const Icon(Icons.add),
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
