import 'package:drift/drift.dart';
import 'package:simple_ledger/data/database/app_database.dart';
import 'package:uuid/uuid.dart';

class RecurringService {
  final AppDatabase db;
  static const _uuid = Uuid();

  RecurringService(this.db);

  static String monthKey(DateTime d) =>
      '${d.year}-${d.month.toString().padLeft(2, '0')}';

  // dayOfMonth == 31 は「月末」センチネル値
  static bool _isDue(RecurringRule rule, DateTime now) {
    if (rule.dayOfMonth == 31) {
      final lastDay = DateTime(now.year, now.month + 1, 0).day;
      return now.day == lastDay;
    }
    return now.day >= rule.dayOfMonth;
  }

  static DateTime _txDate(RecurringRule rule, DateTime now) {
    if (rule.dayOfMonth == 31) {
      return DateTime(now.year, now.month + 1, 0);
    }
    return DateTime(now.year, now.month, rule.dayOfMonth);
  }

  Future<RecurringProcessResult> processToday() async {
    final now = DateTime.now();
    final key = monthKey(now);
    final rules = await db.recurringDao.getActiveRules();
    final logs = await db.recurringDao.getLogsForMonth(key);
    final done = logs.map((l) => l.ruleId).toSet();

    int autoGenerated = 0;
    int pendingCount = 0;

    for (final rule in rules) {
      if (done.contains(rule.id)) continue;
      if (!_isDue(rule, now)) continue;

      if (rule.amount != null) {
        final txId = _uuid.v4();
        final txDate = _txDate(rule, now);
        await db.transactionsDao.insertTransactionWithEntries(
          transaction: FinancialTransactionsCompanion.insert(
            id: txId,
            date: txDate,
            description: rule.name,
            memo: Value(rule.memo),
          ),
          entries: [
            JournalEntriesCompanion.insert(
              transactionId: txId,
              accountId: rule.debitAccountId,
              entryTypeIndex: 0,
              amount: rule.amount!,
            ),
            JournalEntriesCompanion.insert(
              transactionId: txId,
              accountId: rule.creditAccountId,
              entryTypeIndex: 1,
              amount: rule.amount!,
            ),
          ],
        );
        await db.recurringDao.insertLog(RecurringLogsCompanion.insert(
          ruleId: rule.id,
          generatedFor: key,
          transactionId: Value(txId),
        ));
        autoGenerated++;
      } else {
        await db.recurringDao.insertLog(RecurringLogsCompanion.insert(
          ruleId: rule.id,
          generatedFor: key,
        ));
        pendingCount++;
      }
    }

    return RecurringProcessResult(
        autoGenerated: autoGenerated, pendingCount: pendingCount);
  }
}

class RecurringProcessResult {
  final int autoGenerated;
  final int pendingCount;
  const RecurringProcessResult({
    required this.autoGenerated,
    required this.pendingCount,
  });
}
